### ISSUE TITLE
Suggest adding additional roles to rbac

### ISSUE THREAD

**Issue by carpenike** [mintel/dex-k8s-authenticator#161]
Hello!

Got errors because the rbac role does not include the additional resources:

```
- devicetokens
- devicerequests
```

My RBAC role now includes the following rules and the errors went away.

```
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - authcodes
  - authrequests
  - connectors
  - oauth2clients
  - offlinesessionses
  - passwords
  - refreshtokens
  - signingkeies
  - devicetokens
  - devicerequests
  verbs:
  - '*'
```
