### ISSUE TITLE
Specifying caCerts in Helm chart values results in unused CA certificates

### ISSUE THREAD

**Issue by trinitronx** [mintel/dex-k8s-authenticator#42]
Just tested this with the following:

```
caCerts:
  enabled: true
  secrets:
    # Array of Self Signed Certificates
    # cat CA.crt | base64 -w 0
    #
    #     name: The internal k8s name of the secret we create. It's also used in
    #     the volumeMount name. It must respect the k8s naming convension (avoid
    #     upper-case and '.' to be safe).
    #
    #     filename: The filename of the CA to be mounted. It must end in .crt for
    #     update-ca-certificates to work
    #
    #     value: The base64 encoded value of the CA
    #
    - name: ca-cert1
      filename: ca1.crt
      value: "XXXX.....base64 cert 1 here..."
    - name: ca-cert2
      filename: ca2.crt
      value: "XXXX.....base64 cert 2 here..."
```

It looks like the `Deployment` does end up with these listed as mounts:

```
    Mounts:
      /app/config.yaml from config (rw)
      /certs/ca1.crt from login-dex-k8s-authenticator-ca-cert1 (rw)
      /certs/ca2.crt from login-dex-k8s-authenticator-ca-cert2 (rw)
```

However, I still get validation errors.  You can see that these files are actually mounted as directories inside the Pod:

```
# ls -lAR /certs/*
/certs/ca1.crt:
total 0

/certs/ca2.crt:
total 0
```

If we inspect the file location on the Kubernetes host machine, we can see that it treats only the `name` as the true filename, while `ca1.crt` and `ca2.crt` are directories:

```
core@ip-123-45-6-78 ~ $ sudo ls -lA /var/lib/kubelet/pods/9a98a5d0-7405-11e8-a008-0eb17fad7d94/volumes/kubernetes.io~secret/login-dex-k8s-authenticator-ca-cert1/
total 0
drwxr-xr-x. 2 root root 60 Jun 19 21:13 ..2018_06_19_21_13_25.540309803
lrwxrwxrwx. 1 root root 31 Jun 19 21:13 ..data -> ..2018_06_19_21_13_25.540309803
lrwxrwxrwx. 1 root root 15 Jun 19 21:13 ca-cert1 -> ..data/ca-cert1
drwxrwxrwt. 2 root root 40 Jun 19 21:13 ca1.crt

core@ip-123-45-6-78 ~ $ sudo ls -lA /var/lib/kubelet/pods/9a98a5d0-7405-11e8-a008-0eb17fad7d94/volumes/kubernetes.io~secret/login-dex-k8s-authenticator-ca-cert2/
total 0
drwxr-xr-x. 2 root root 60 Jun 19 21:13 ..2018_06_19_21_13_25.626894990
lrwxrwxrwx. 1 root root 31 Jun 19 21:13 ..data -> ..2018_06_19_21_13_25.626894990
lrwxrwxrwx. 1 root root 15 Jun 19 21:13 ca-cert2 -> ..data/ca-cert2
drwxrwxrwt. 2 root root 40 Jun 19 21:13 ca2.crt
```

So, only those names `ca-cert2` and `ca-cert1` are valid files as far as the mountable `Secret` data content on the host looks.

Looks like issues assumed fixed in #35 & #36 are still problems?

As it turns out, the `subPath` attribute for a volume mount does not actually work on files (see: kubernetes/kubernetes#62156 ).  This may be a bug in kubernetes, yet it it's current functional state, trying to use `caCerts` in this Helm chart does not work.  This `subPath` as directory mount behavior matches my experience since `subPath` was introduced, but the docs don't make it clear that plain file mounts are not yet supported.
