### ISSUE TITLE
use ENV vars in config file

### ISSUE THREAD

**Issue by AlexMorreale** [mintel/dex-k8s-authenticator#45]
I'd love to be able use ENV vars from a kubernetes secret in the config file.   
Right now we have to make the whole config secret instead of configmap.

I saw this in the change log: 
```
Added envar substitutions. Can now generate a config based on values in the environment (useful for the client_secret).
```

would this unreleased feature allow me drop `client_secret: <redacted> ` from my configmap and just use an ENV var to specifiy the `client_secret`.

Also love the tool. It makes it so much easy for our developers gain kubectl access. Thanks for writing this tool!.

**Comment by AlexMorreale** [comment]
Looks like the code in the PR for that change only happens when you dont specify and a config file?

Correct me if i am wrong here.

**Comment by nabadger** [comment]
@AlexMorreale  thanks for feedback :)

The `latest` image should support this but there's a limitation in the Helm template at the moment as it doesn't let you pass in `env` to the podspec (I'll create an issue to track/add this as it's simple enough).

If you're rolling your own manifests, here's how you can do it.

dex-k8s-authenticator config:

```yaml
listen: http://0.0.0.0:5555
debug: false
clusters:
- client_id: my-cluster
  client_secret: ${CLIENT_SECRET}
  description: minikube
  issuer: http://dex.minikube.test
  k8s_ca_uri: http://ca.example.com
  k8s_master_uri: http://my-cluster.example.com
  name: my-cluster
  redirect_uri: http://auth.minikube.test/callback/my-cluster
```
kubernetes secret:

```yaml
apiVersion: v1
data:
  client_secret: <base64 encoded secret>
kind: Secret
metadata:
  name: dex-auth-secrets
  namespace: default
type: Opaque
```

pod-spec

```yaml
  ...
  spec:
      containers:
      - args:
        - --config
        - config.yaml
        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: dex-auth-secrets
...
```

**Comment by AlexMorreale** [comment]
luckily i am rolling my own manifests(gives us more flexibility and allows us to use traefik as our ingress infront of them)

I actually tried something similar to this and im getting a client_

```
Failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
``` 
when i return from dex to dex-k8s-authenticator

**Comment by AlexMorreale** [comment]
oddly enough this works if i just use a straight up environment variable not from a secret

```
    spec:                    
      containers:            
      - name: dex-k8s-authenticator
        image: "mintel/dex-k8s-authenticator:latest"
        args: [ "--config", "config.yaml" ]
        ports:               
        - name: web          
          containerPort: 5555
          protocol: TCP      
        volumeMounts:        
        - name: config       
          subPath: config.yaml
          mountPath: /app/config.yaml
        - name: tls          
          mountPath: /etc/dex-k8s-authenticator/tls
        env:                 
        - name: CLIENT_SECRET                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          value: <REMOVED>
```

```
---                          
apiVersion: v1               
kind: ConfigMap              
metadata:                    
  name: dex-k8s-authenticator
  namespace: kube-system     
  labels:                    
    app: dex-k8s-authenticator
data:                        
  config.yaml: |             
    listen: https://0.0.0.0:5555
    tls_cert: /etc/dex-k8s-authenticator/tls/tls.crt
    tls_key: /etc/dex-k8s-authenticator/tls/tls.key
    debug: true              
    logo_uri: https://www.ezcater.com/logo.png
    clusters:                
    - client_id: staging-dex-k8s-authenticator
      client_secret: ${CLIENT_SECRET}
      description: ezCater Kubernetes US-EAST-1 Staging Cluster
      issuer: https://dex.staging-ezcater.net
      k8s_ca_uri: https://dex.
      k8s_master_uri: https://kube-master.kubernetes-useast1
      name: kubernetes-useast1-staging
      redirect_uri: https://login2kubernetes.
      short_description: kubernetes-useast1.
```
