### ISSUE TITLE
Ingress with path rule does not work

### ISSUE THREAD

**Issue by luispollo** [mintel/dex-k8s-authenticator#51]
It looks like the code has hard-coded absolute paths for the static assets (`/static`), so if you use a path rule in the ingress, only the index page loads, but the assets don't. I'm using the NXING ingress controller and tried different combinations of annotations hoping that would fix the problem, but couldn't make it work.

Sample ingress config:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/base-url-scheme: https
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    # ...
  name: dex-login-dex-k8s-authenticator
  namespace: dex
spec:
  rules:
  - host: infra.hppipeline.com
    http:
      paths:
      - backend:
          serviceName: dex-login-dex-k8s-authenticator
          servicePort: 5555
        path: /login
```

P.S. Thanks for contributing this -- it's a pretty useful tool!
