### ISSUE TITLE
livenessProbe and readinessProbe paths

### ISSUE THREAD

**Issue by kostyrev** [mintel/dex-k8s-authenticator#81]
```
-     chart: dex-k8s-authenticator-0.1.2
+     chart: dex-k8s-authenticator-1.1.1
      release: dex-k8s-authenticator
      heritage: Tiller
  spec:
    template:
      metadata:
        labels:
          app: dex-k8s-authenticator
      spec:
        containers:
        - name: dex-k8s-authenticator
          image: "mintel/dex-k8s-authenticator:1.1.0"
          livenessProbe:
            httpGet:
-             path: /
+             path: /healthz
              port: http
          readinessProbe:
            httpGet:
-             path: /
+             path: /healthz
              port: http
```
Is that what it should be set to by default? 
curl for /healthz shows the same "Generate Kubernetes Token" page as before.
