### ISSUE TITLE
Added extra-scopes to kubeconfig once generated

### ISSUE THREAD

**Issue by nickmintel** [mintel/dex-k8s-authenticator#82]
Code calls

`scopes = append(scopes, "openid", "profile", "email", "offline_access", "groups")`

Should add this to the generated kubeconfig as well:

```
- name: ...
  user:
    auth-provider:
      config:
        client-id: ...
        client-secret: ...
        extra-scopes: openid,profile,email,offline_access,groups
```
